name: CI

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install


      # - name: Run Tests
      #   run: npm test

      - name: Run Linting
        run: yarn run lint
      
      - name: Build
        run: yarn run build
        
      # - name: Pull to main branch if build passes
      #   if: success()
      #   run: |
      #       git switch 'main'
      #       git pull origin dev